### ISSUE TITLE
Editing a selected inventory

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/climate#129]
This should be the part where we select a individual item, and redirect to [id].js . If the id is valid and consists of a selected inventory, we should populate a form type page where the user can edit information.

## Acceptance Criteria
1. Build a form layout for the page. No need to abstract it for now, quickly the better.
2. Build the edit functionality for this. Can re-use the add inventory form logic but add logic to populate of course.
3. Saving when change is detected should open a modal that asks the users to confirm if necessary. This prevent accidental go backs and redirects after an edit has occurred.
4. Build a ux before starting this work.

**Comment by earmuff-jam** [comment]
The basics for this was completed with ticket #128 , keeping this for any unforeseen changes.
