### ISSUE TITLE
Flush existing maintenance requests

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/climate#131]
## Acceptance Criteria

1. Revamp "create maintenance request" form to create new maintenance requests. Allow users to freely add / remove selected inventory items to and from cyclic maintenance. If an item is disbanded, present modal to approve the change like a confirmation modal so that users are aware of their actions. We want to also highlight that it will change some aspects of the app.
2. Maintenance request can be of many types. Daily, weekly, bi-weekly, monthly, every 6 months or every year or more. We want to let the users make their own requests. After their form is built, they have to move their inventory items to their created forms. This can be just like how they need to move for categories.
3. Color code is required here. 
4. We should also have location to display reports for these. Ux is required for this as well. The color codes should transpire to the reports. Aka Monthly marked blue should also have blue on the reports. There should be dots on the top of the reports ( like a tab form ) that should show how many items are due, or something that users can quickly glance and note about their maintenance. This is one of the main features of the app. Lets bring more than just a crud operation here.
5. More to follow.

**Comment by mohit2530** [comment]
1. Users view alert if they have overdue items that can be dismissed. but is presented everytime they come back in again.
2. Users can pin maintenance requests. Only two for now. These pinned can be shown in overview page.
3. Items due and Total items are displayed in the card layout, add graph below it for overDue vs Month. like how many items are overdue in x month.
4. Export this graph ( idk how )
5. Recent activities list opens up on the side.
6. Add maintenance form on the side small icon button only.

Ux initial design from - 
![image](https://github.com/earmuff-jam/climate/assets/44540219/f0bbc1c4-4216-4355-898b-5627e107cd99)

**Comment by earmuff-jam** [comment]
Pending work that remains 
1. Build graph modules.
2. Build recent activities.
3. Overdue items must be also added to the top card component
