### ISSUE TITLE
Build low on stock table

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate#144]
## Acceptance Criteria
1. Build low on stock table. this table is built to show the items that are low on stock. They should just simply display a list of names of all the items that fall below the threshold for each category.
2. Cleanup other a/o if possible. maybe we need to rethink how to use the table. some of the custom functionalities like filter and sort might be useful to use from other lib.

**Comment by mohit2530** [comment]
Ticket for grid vs list is #148
