### ISSUE TITLE
Maintenance Request Form Updates.

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/climate#46]
Maintenance Request form requires a few upgrades.

```
ID - id of each maintenance request
Description - description of each maintenance request.
Status - current status of the the request.
Submitted - when was this request submitted.
Action - what action has happened on this request.
Complaint - what complain did the tenant make ?
Notes - what is the notes of the owner or the cleanup crew ?
```
Notes, Complaint and Description can be of free text.

1. Currently there is no form where you can fill these things out. It is ok. We can assume that users created some form somewhere. We have to build a table to store this form in the supabase toolkit. 
2. The table should show each maintenance request for each property. a possibility of 1 to many mapping. therefore it would be wise to store the property id as foreign key. 
3. We should also probably reference the owner ( profile table ) and its co-related ( tenant ) - NOT BUILT YET. We can assume `tenant.id` and `tenant.firstname` + `tenant.lastname`. We can also add them later with an alter command not a big deal.
4. As maintenance forms kind of also act like a tracking system for what repairs and things have been done, we would possibly be inclined to create a history table for this matter. For now, however, we should just not think that direction.
5. We should rather provide users the ability to filter on request forms - `6 months` , `1 year` and `Till date`. Maybe a `custom` date range too if the task is not too daunting.
6. A possibility that we might want to think is to route to new page `maintenance/{id}` if ONLY required and we have more details to display on the form. 

Maybe this is a just too much on for a single issue. We can actually create 6 individual tickets to handle each one of them. Regardless, lets keep this as the source of truth for any issue.

**Comment by mohit2530** [comment]
@sujan-dahal please add your thoughts.

**Comment by earmuff-jam** [comment]
Also one more thought, the `Payment Form` inside each property also displays and / or follows the same pattern. Should we reuse the component to structure it for both components ?

**Comment by mohit2530** [comment]
Í
<img width="865" alt="Screenshot 2023-05-16 at 8 59 10 PM" src="https://github.com/earmuff-jam/climate/assets/44540219/9c7b7ddc-0e9f-431f-b8e6-27ccf07f0258">

<img width="535" alt="Screenshot 2023-05-16 at 8 58 03 PM" src="https://github.com/earmuff-jam/climate/assets/44540219/19cd344b-f6ed-420a-a076-b348d2cd1587">

<img width="668" alt="Screenshot 2023-05-16 at 8 57 54 PM" src="https://github.com/earmuff-jam/climate/assets/44540219/16891acc-88b1-48e7-b4b9-3a741055dd3f">

<img width="847" alt="Screenshot 2023-05-16 at 8 57 45 PM" src="https://github.com/earmuff-jam/climate/assets/44540219/6b2a3526-b151-460d-ad79-1d1cb8c70fde">

**Comment by mohit2530** [comment]
https://github.com/earmuff-jam/climate/issues/84 will solve resulting changes and bugs that are brought by this ticket.
