### ISSUE TITLE
[Spike] - Periodic Evaluation of Properties

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/climate#78]
Incorporate ability to have periodic evaluation of properties.

**Comment by mohit2530** [comment]
A property management company can support periodic evaluation of rental properties in several ways, including:

1. Regular property inspections: The property management company can conduct regular inspections of the rental properties to identify any issues or maintenance needs. These inspections can be scheduled quarterly, semi-annually, or annually, depending on the agreement between the property owner and the management company.

2. Analysis of rental market trends: The property management company can keep track of the rental market trends in the area where the rental properties are located. This can help determine the rental rates for the properties and identify any changes in the demand for rental properties in the area.

3. Benchmarking against similar properties: The property management company can benchmark the rental properties against similar properties in the area to identify any areas for improvement or opportunities for growth. This can include comparing rental rates, amenities, and overall condition of the properties.

4. Financial analysis: The property management company can provide financial analysis of the rental properties, including evaluating the rental income, expenses, and return on investment. This can help identify any areas where the property can be optimized to increase profitability.

5. Communication with property owners: The property management company can maintain open communication with the property owners to discuss any concerns or feedback regarding the rental properties. This can help identify any areas for improvement and ensure that the property is being managed in a way that meets the owner's expectations.

By implementing these strategies, a property management company can support the periodic evaluation of rental properties, helping property owners optimize the profitability of their investments and ensure that their properties remain competitive in the rental market.

**Comment by mohit2530** [comment]
**HOW CAN WE INTRODUCE ABOVE SAID FEATURES**

1. conduct inspections using a mobile device, capturing photos and notes that can be uploaded to a centralized platform for review. This can help streamline the inspection process, reducing the need for manual data entry and ensuring that the inspection data is accurate and up-to-date.

2. analyze rental market trends by providing access to market data and analytics. This can include data on rental rates, occupancy rates, and market trends, helping property managers stay informed about the rental market in the area where the rental properties are located.

3. benchmark against similar properties by comparing rental rates, amenities, and other key factors across different properties in the area.

4. Financial analysis by gathering financial data and analytics. This can include data on rental income, expenses, and return on investment, helping property managers optimize the profitability of the rental properties.

5. Send messages, alerts, and notifications to property owners. This can help ensure that property owners are kept informed about the status of their rental properties and can provide feedback or input as needed.

**Comment by mohit2530** [comment]
<img width="696" alt="Screenshot 2023-05-12 at 8 41 01 AM" src="https://github.com/earmuff-jam/climate/assets/44540219/46d79ddb-3df1-4792-a150-d4b457a0ce7b">

**Comment by earmuff-jam** [comment]
https://dpassupport.golearnportal.org/Resource_Center_Files/QRGs/PA_Generating%20Inventories%20QRG.pdf

Cyclic Inventories for Maintenance.
